
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class caja
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public caja()
    {

        this.cierre_caja = new HashSet<cierre_caja>();

        this.detalle_forma_cobro = new HashSet<detalle_forma_cobro>();

    }


    public int id_caja { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public bool activo { get; set; }

    public string codigo { get; set; }

    public string descripcion { get; set; }

    public int id_organizacion { get; set; }

    public int id_sucursal { get; set; }

    public string nombre { get; set; }

    public bool predeterminado { get; set; }

    public Nullable<int> id_punto_de_venta { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<cierre_caja> cierre_caja { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro { get; set; }

}

}
