
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Clientes
{

    public string empresa { get; set; }

    public string codigo { get; set; }

    public string nombre_fiscal { get; set; }

    public string nombre_comercial { get; set; }

    public string provincia { get; set; }

    public string ciudad { get; set; }

    public string parroquia { get; set; }

    public string codigo_postal { get; set; }

    public string telefono { get; set; }

    public string telefono2 { get; set; }

    public string direccion { get; set; }

    public string correo { get; set; }

    public Nullable<int> id_vendedor { get; set; }

    public string vendedor { get; set; }

    public string categoria_empresa { get; set; }

    public int tipo_empresa { get; set; }

    public string origen_ingreso { get; set; }

    public string zona { get; set; }

    public string sector { get; set; }

    public string forma_de_pago { get; set; }

    public string lista_de_precio { get; set; }

    public string transportista { get; set; }

    public string condicion_pago { get; set; }

    public Nullable<int> metodo_facturacion { get; set; }

    public string lista_descuentos { get; set; }

    public Nullable<bool> enviar_email { get; set; }

    public string forma_de_pago_SRI { get; set; }

}

}
