//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes2
    {
        public int id_organizacion { get; set; }
        public string empresa { get; set; }
        public string codigo { get; set; }
        public string nombre_comercial { get; set; }
        public int id_empresa { get; set; }
        public string nombre_fiscal { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string parroquia { get; set; }
        public string codigo_postal { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string tipo_empresa { get; set; }
        public decimal credito_maximo { get; set; }
        public decimal credito_utilizado { get; set; }
        public string forma_pago { get; set; }
        public string dias_pago { get; set; }
        public string agente_comercial { get; set; }
        public Nullable<int> id_agente_comercial { get; set; }
        public string zona { get; set; }
        public string lista_precio { get; set; }
        public string descuento { get; set; }
        public string metodo_de_facturacion { get; set; }
        public string canal { get; set; }
        public string categoria_empresa { get; set; }
        public string tipo_identificacion { get; set; }
        public bool indicador_genera_autoconsumo { get; set; }
    }
}
