//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes_actualizacion
    {
        public string id_empresa { get; set; }
        public string empresa { get; set; }
        public string codigo_anterior { get; set; }
        public string codigo_actual { get; set; }
    }
}
