
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class cobro
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public cobro()
    {

        this.detalle_forma_cobro = new HashSet<detalle_forma_cobro>();

        this.detalle_forma_cobro1 = new HashSet<detalle_forma_cobro>();

    }


    public int id_cobro { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public string archivo { get; set; }

    public Nullable<int> autorizacion_impresion { get; set; }

    public string codigo_movil { get; set; }

    public string descripcion { get; set; }

    public string descripcion2 { get; set; }

    public string descripcion_anulacion { get; set; }

    public string documento_referencia { get; set; }

    public int estado { get; set; }

    public System.DateTime fecha { get; set; }

    public Nullable<System.DateTime> fecha_contabilizacion { get; set; }

    public Nullable<System.DateTime> fecha_registro { get; set; }

    public Nullable<int> id_dispositivo_sincronizacion { get; set; }

    public int id_organizacion { get; set; }

    public Nullable<bool> indicador_prorrateado_detalles { get; set; }

    public bool indicador_tiene_cheques { get; set; }

    public bool indicador_tiene_posfechados { get; set; }

    public string numero { get; set; }

    public decimal valor { get; set; }

    public Nullable<int> id_asiento { get; set; }

    public Nullable<int> id_asiento_protesto { get; set; }

    public Nullable<int> id_cuenta_bancaria_organizacion { get; set; }

    public int id_documento { get; set; }

    public int id_empresa { get; set; }

    public Nullable<int> id_forma_pago { get; set; }

    public Nullable<int> id_recaudador { get; set; }

    public int id_sucursal { get; set; }

    public Nullable<bool> es_microcobro_bp { get; set; }

    public Nullable<int> id_interfaz_contable_proceso { get; set; }

    public Nullable<int> id_pago_plux { get; set; }

    public Nullable<int> estado_consolidado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro { get; set; }

    public virtual empresa empresa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<detalle_forma_cobro> detalle_forma_cobro1 { get; set; }

}

}
