
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cobros_Consolidado
{

    public string empresa { get; set; }

    public string sucursal { get; set; }

    public string codigo_cobro { get; set; }

    public string descripcion { get; set; }

    public string descripcion2 { get; set; }

    public int estado { get; set; }

    public Nullable<System.DateTime> fecha_aplicacion { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public decimal valor { get; set; }

    public string codigo { get; set; }

    public string nombre_comercial { get; set; }

    public string numero { get; set; }

    public Nullable<System.DateTime> fecha_factura { get; set; }

    public Nullable<System.DateTime> fecha_vencimiento { get; set; }

    public string descripcion_factura { get; set; }

    public string categoria { get; set; }

    public Nullable<int> id_vendedor { get; set; }

    public string vendedor { get; set; }

    public Nullable<decimal> total { get; set; }

    public string forma_pago { get; set; }

}

}
