
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Consulta_Consolidado_Cierres
{

    public int id_organizacion { get; set; }

    public string empresa { get; set; }

    public int id_sucursal { get; set; }

    public string sucursal { get; set; }

    public string numero_consolidado { get; set; }

    public decimal valor_total { get; set; }

    public string fecha { get; set; }

    public Nullable<int> estado { get; set; }

    public string nom_estado { get; set; }

    public int id_consolidado_cierre { get; set; }

}

}
