
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class consolidado_cierre
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public consolidado_cierre()
    {

        this.devolucion_consolidado_cierre = new HashSet<devolucion_consolidado_cierre>();

        this.detalle_consolidado_cierre = new HashSet<detalle_consolidado_cierre>();

    }


    public int id_consolidado_cierre { get; set; }

    public int id_organizacion { get; set; }

    public int id_sucursal { get; set; }

    public string numero_consolidado { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public Nullable<int> estado { get; set; }

    public decimal valor_total { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<devolucion_consolidado_cierre> devolucion_consolidado_cierre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<detalle_consolidado_cierre> detalle_consolidado_cierre { get; set; }

}

}
