//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costos_MOD
    {
        public int id_orden_fabricacion { get; set; }
        public string orden_fabricacion { get; set; }
        public string operacion { get; set; }
        public string nombre_maquina { get; set; }
        public decimal horas_hombre { get; set; }
        public decimal horas_hombre_originales { get; set; }
        public decimal horas_maquina { get; set; }
        public decimal horas_maquina_originales { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
    }
}
