//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costos_MP_ME
    {
        public string lote { get; set; }
        public string codigo_categoria_producto { get; set; }
        public string codigo_producto { get; set; }
        public string producto { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<decimal> consumo { get; set; }
        public Nullable<double> receta { get; set; }
        public Nullable<double> desperdicio { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
        public int id_orden_fabricacion { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<decimal> cantidad_a_producir { get; set; }
    }
}
