
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Costos_Indirectos
{

    public int id_orden_fabricacion { get; set; }

    public Nullable<decimal> cantidad { get; set; }

    public Nullable<decimal> costo_total { get; set; }

    public Nullable<decimal> costo_unitario { get; set; }

}

}
