//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion_cabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacion_cabecera()
        {
            this.cotizacion_detalle = new HashSet<cotizacion_detalle>();
            this.relacion_cotizacion_ganadora_perdedora = new HashSet<relacion_cotizacion_ganadora_perdedora>();
            this.relacion_cotizacion_ganadora_perdedora1 = new HashSet<relacion_cotizacion_ganadora_perdedora>();
        }
    
        public int id_cotizacion { get; set; }
        public System.DateTime fecha_documento { get; set; }
        public decimal valor_total { get; set; }
        public byte anulada { get; set; }
        public byte indicador_ganadora { get; set; }
        public byte indicador_perdedora { get; set; }
        public int id_empresaOasis { get; set; }
        public int id_cliente { get; set; }
        public string forma_pago { get; set; }
        public int dias_periodo_validez { get; set; }
        public int meses_tiempo_garantia { get; set; }
        public int dias_tiempo_entrega { get; set; }
        public string persona_contacto { get; set; }
        public int id_vendedor { get; set; }
    
        public virtual cotizacion_cabecera cotizacion_cabecera1 { get; set; }
        public virtual cotizacion_cabecera cotizacion_cabecera2 { get; set; }
        public virtual empresaOasis empresaOasis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacion_detalle> cotizacion_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relacion_cotizacion_ganadora_perdedora> relacion_cotizacion_ganadora_perdedora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relacion_cotizacion_ganadora_perdedora> relacion_cotizacion_ganadora_perdedora1 { get; set; }
    }
}
