//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class despacho
    {
        public int id_despacho { get; set; }
        public int id_picking { get; set; }
        public int id_factura { get; set; }
        public Nullable<System.DateTime> fecha_inicio_desp { get; set; }
        public Nullable<System.DateTime> fecha_fin_desp { get; set; }
        public int estado { get; set; }
        public int id_usuario { get; set; }
    }
}
