
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class detalle_consolidado_cierre
{

    public int id_detalle_conso_cierre { get; set; }

    public int id_consolidado_cierre { get; set; }

    public int id_organizacion { get; set; }

    public int id_sucursal { get; set; }

    public int id_cobro { get; set; }

    public int id_detalle_forma_cobro { get; set; }

    public int id_detalle_cobro { get; set; }

    public string numero_consolidado { get; set; }

    public string numero { get; set; }

    public string numero_ant { get; set; }

    public decimal valor { get; set; }

    public decimal valor_total { get; set; }

    public string cobrador { get; set; }

    public int id_forma_pago { get; set; }

    public Nullable<System.DateTime> fecha_pago { get; set; }

    public string documento { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }



    public virtual consolidado_cierre consolidado_cierre { get; set; }

}

}
