
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class detalle_forma_cobro
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public detalle_forma_cobro()
    {

        this.detalle_cierre_caja = new HashSet<detalle_cierre_caja>();

    }


    public int id_detalle_forma_cobro { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public string autorizacion { get; set; }

    public decimal base_imponible_diferente_cero { get; set; }

    public decimal base_imponible_tarifa_cero { get; set; }

    public string descripcion { get; set; }

    public string documento_referencia { get; set; }

    public string documento_referencia_protesto { get; set; }

    public Nullable<System.DateTime> fecha_protesto { get; set; }

    public Nullable<System.DateTime> fecha_voucher { get; set; }

    public Nullable<int> id_dispositivo_sincronizacion { get; set; }

    public int id_organizacion { get; set; }

    public int id_sucursal { get; set; }

    public Nullable<decimal> impuesto_comision { get; set; }

    public bool indicador_cargar_cliente_protesto { get; set; }

    public bool indicador_cheque_posfechado { get; set; }

    public bool indicador_cheque_protestado { get; set; }

    public bool indicador_cobrado { get; set; }

    public bool indicador_valor_retencion_fuente { get; set; }

    public bool indicador_valor_retencion_iva { get; set; }

    public Nullable<decimal> interes { get; set; }

    public string lote { get; set; }

    public Nullable<decimal> monto_iva { get; set; }

    public string numero_tarjeta { get; set; }

    public Nullable<decimal> porcentaje_comision { get; set; }

    public Nullable<decimal> retencion_fuente { get; set; }

    public Nullable<decimal> retencion_iva { get; set; }

    public Nullable<int> secuencial { get; set; }

    public decimal valor { get; set; }

    public Nullable<decimal> valor_comision { get; set; }

    public Nullable<decimal> valor_pagado { get; set; }

    public Nullable<decimal> valor_pagado_calculado { get; set; }

    public Nullable<decimal> valor_protestado { get; set; }

    public Nullable<int> id_anticipo_cliente { get; set; }

    public Nullable<int> id_asiento { get; set; }

    public Nullable<int> id_banco { get; set; }

    public Nullable<int> id_caja { get; set; }

    public Nullable<int> id_cobro { get; set; }

    public Nullable<int> id_cobro_tarjeta { get; set; }

    public Nullable<int> id_cuenta_bancaria_organizacion { get; set; }

    public Nullable<int> id_cuenta_bancaria_organizacion_protesto { get; set; }

    public Nullable<int> id_cuenta_contable_forma_cobro { get; set; }

    public Nullable<int> id_dimension_contable1 { get; set; }

    public Nullable<int> id_dimension_contable2 { get; set; }

    public Nullable<int> id_dimension_contable3 { get; set; }

    public Nullable<int> id_dimension_contable4 { get; set; }

    public Nullable<int> id_dimension_contable5 { get; set; }

    public int id_forma_pago { get; set; }

    public Nullable<int> id_forma_pago_protesto { get; set; }

    public Nullable<int> id_plan_tarjeta_credito { get; set; }

    public Nullable<int> id_punto_venta { get; set; }

    public Nullable<int> id_tarjeta_credito { get; set; }

    public string nombre_retencion_bien_servicio { get; set; }

    public Nullable<System.DateTime> fecha_documento { get; set; }

    public Nullable<int> id_cobro_prestamo { get; set; }



    public virtual caja caja { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<detalle_cierre_caja> detalle_cierre_caja { get; set; }

}

}
