
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleOCEnlazada
{

    public string empresa { get; set; }

    public string proveedor { get; set; }

    public string ruc_proveedor { get; set; }

    public int id_oc { get; set; }

    public string secuencial { get; set; }

    public System.DateTime fecha { get; set; }

    public string departamento { get; set; }

    public int codigo_producto { get; set; }

    public string descripcion_producto { get; set; }

    public string categoria_producto { get; set; }

    public string um_producto { get; set; }

    public decimal cantidad_producto { get; set; }

    public decimal valor_linea { get; set; }

    public decimal valor_total { get; set; }

}

}
