
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class detalle_lista_precio
{

    public int id_detalle_lista_precio { get; set; }

    public int id_lista_precio { get; set; }

    public int id_producto_inst { get; set; }

    public decimal precio_mayor { get; set; }

    public decimal precio_menor { get; set; }

    public decimal porcentaje { get; set; }



    public virtual lista_precio lista_precio { get; set; }

    public virtual producto_instituciones producto_instituciones { get; set; }

}

}
