
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Detalle_Cobros
{

    public int id_organizacion { get; set; }

    public string empresa { get; set; }

    public int id_sucursal { get; set; }

    public string sucursal { get; set; }

    public int id_cobro { get; set; }

    public int id_detalle_cobro { get; set; }

    public string numero { get; set; }

    public System.DateTime fecha_cobro { get; set; }

    public string fecha_crea_co { get; set; }

    public int cod_cliente { get; set; }

    public string identificacion { get; set; }

    public string cliente { get; set; }

    public decimal valor_total { get; set; }

    public Nullable<int> id_recaudador { get; set; }

    public string nom_recaudador { get; set; }

    public string cobrador { get; set; }

    public int id_forma_pago { get; set; }

    public string cod_forma_pago { get; set; }

    public string forma_pago { get; set; }

    public decimal valor_cobro { get; set; }

    public Nullable<int> id_banco { get; set; }

    public string nom_banco { get; set; }

    public string num_documento { get; set; }

    public string fecha_pago { get; set; }

    public int estado { get; set; }

    public string nom_estado { get; set; }

    public int id_usuario { get; set; }

    public string num_cierre { get; set; }

    public int id_detalle_forma_cobro { get; set; }

    public string factura { get; set; }

    public string fecha_factura { get; set; }

    public Nullable<decimal> valor_factura { get; set; }

    public int estado_consolidado { get; set; }

    public int cod_tabla { get; set; }

    public string num_ant { get; set; }

}

}
