
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Detalle_Vendedores
{

    public string cobrador { get; set; }

    public string nom_cobrador { get; set; }

    public int id_consolidado_cierre { get; set; }

    public Nullable<decimal> total_cobro { get; set; }

}

}
