//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_roles_usuario
    {
        public int id_detalle_roles_usuario { get; set; }
        public int id_usuario { get; set; }
        public int id_rol { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual usuarioOasis usuario { get; set; }
    }
}
