
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class detalle_cierre_caja
{

    public int id_detalle_cierre_caja { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public Nullable<int> id_dispositivo_sincronizacion { get; set; }

    public int id_organizacion { get; set; }

    public int id_sucursal { get; set; }

    public decimal valor { get; set; }

    public Nullable<int> id_anticipo_cliente { get; set; }

    public Nullable<int> id_cierre_caja { get; set; }

    public Nullable<int> id_detalle_denominacion_forma_cobro { get; set; }

    public Nullable<int> id_detalle_forma_cobro { get; set; }

    public Nullable<int> id_interfaz_contable_proceso { get; set; }



    public virtual cierre_caja cierre_caja { get; set; }

    public virtual detalle_forma_cobro detalle_forma_cobro { get; set; }

}

}
