
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class devolucion_consolidado_cierre
{

    public int id_devolucion_cons_cierre { get; set; }

    public int id_consolidado_cierre { get; set; }

    public int id_organizacion { get; set; }

    public int id_sucursal { get; set; }

    public string numero_consolidado { get; set; }

    public decimal valor { get; set; }

    public int cant_reg { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }



    public virtual consolidado_cierre consolidado_cierre { get; set; }

}

}
