//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public direccion_empresa()
        {
            this.factura_cliente = new HashSet<factura_cliente>();
        }
    
        public int id_direccion_empresa { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo_postal { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_dispositivo_sincronizacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public bool indicador_direccion_envio { get; set; }
        public bool indicador_direccion_factura { get; set; }
        public bool indicador_direccion_principal { get; set; }
        public Nullable<bool> indicador_paraiso_fiscal { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public int id_ciudad { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_parroquia { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cliente> factura_cliente { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ubicacion ubicacion { get; set; }
    }
}
