//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVP
    {
        public int ID { get; set; }
        public string Empresa { get; set; }
        public string Tipo_documento { get; set; }
        public Nullable<System.DateTime> Fecha_factura { get; set; }
        public string Ciudad { get; set; }
        public string Provincia { get; set; }
        public string Parroquia { get; set; }
        public string Tipo_cliente { get; set; }
        public string Canal { get; set; }
        public string RUC { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> id_motivo_nota_credito_cliente { get; set; }
        public string Secuencial_documento { get; set; }
        public Nullable<bool> indicador_afecta_devolucion { get; set; }
        public string Código_producto { get; set; }
        public string Código_MBA { get; set; }
        public string Producto { get; set; }
        public string Categoría { get; set; }
        public string Subcategoría { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Valor_total { get; set; }
        public string Tipo_venta { get; set; }
        public string codigo { get; set; }
        public Nullable<int> Cod__Vendedor { get; set; }
        public string Vendedor { get; set; }
        public string NC { get; set; }
        public string Descripción_NC { get; set; }
        public Nullable<System.DateTime> Fecha_NC { get; set; }
        public string clave_acceso { get; set; }
        public int id_factura_cliente { get; set; }
        public string memo { get; set; }
        public string zona { get; set; }
    }
}
