
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DVP_Credito
{

    public int ID { get; set; }

    public string Empresa { get; set; }

    public string TipoDocumento { get; set; }

    public Nullable<System.DateTime> FechaFactura { get; set; }

    public string Ciudad { get; set; }

    public string Provincia { get; set; }

    public string Parroquia { get; set; }

    public string TipoCliente { get; set; }

    public string Canal { get; set; }

    public string RUC { get; set; }

    public string Cliente { get; set; }

    public int id_motivo_nota_credito_cliente { get; set; }

    public string SecuencialDocumento { get; set; }

    public bool indicador_afecta_devolucion { get; set; }

    public string CodigoProducto { get; set; }

    public string CodigoMBA { get; set; }

    public string Producto { get; set; }

    public string Categoría { get; set; }

    public string Subcategoría { get; set; }

    public string UM { get; set; }

    public Nullable<decimal> Cantidad { get; set; }

    public Nullable<decimal> Valortotal { get; set; }

    public string TipoVenta { get; set; }

    public string codigo { get; set; }

    public int CodVendedor { get; set; }

    public string Vendedor { get; set; }

    public string NC { get; set; }

    public string DescripcionNC { get; set; }

    public Nullable<System.DateTime> FechaNC { get; set; }

    public string clave_acceso { get; set; }

    public int id_factura_cliente { get; set; }

    public string memo { get; set; }

    public Nullable<int> id_sucursal { get; set; }

    public string zona { get; set; }

}

}
