//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.factura_cliente = new HashSet<factura_cliente>();
            this.direccion_empresa = new HashSet<direccion_empresa>();
        }
    
        public int id_empresa { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_entidad_origen { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public bool activo { get; set; }
        public string codigo { get; set; }
        public string codigo_alterno { get; set; }
        public string cuenta_facebook { get; set; }
        public string cuenta_twitter { get; set; }
        public string descripcion { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string email3 { get; set; }
        public string email4 { get; set; }
        public string email5 { get; set; }
        public Nullable<int> genero { get; set; }
        public Nullable<int> id_dispositivo_sincronizacion { get; set; }
        public int id_organizacion { get; set; }
        public int id_sucursal { get; set; }
        public string identificacion { get; set; }
        public bool indicador_aplica_descuento { get; set; }
        public bool indicador_cliente { get; set; }
        public bool indicador_cliente_proveedor { get; set; }
        public bool indicador_empleado { get; set; }
        public bool indicador_entidad_publica { get; set; }
        public bool indicador_floricola { get; set; }
        public bool indicador_proveedor { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
        public string nombre_comercial { get; set; }
        public string nombre_fiscal { get; set; }
        public string pagina_web { get; set; }
        public string texto_busqueda { get; set; }
        public int tipo_empresa { get; set; }
        public Nullable<int> id_categoria_empresa { get; set; }
        public Nullable<int> id_conjunto_atributo_cliente { get; set; }
        public Nullable<int> id_conjunto_atributo_proveedor { get; set; }
        public Nullable<int> id_estado_civil { get; set; }
        public Nullable<int> id_origen_ingresos { get; set; }
        public int id_tipo_identificacion { get; set; }
        public bool indicador_bloqeuado_generacion_archivo { get; set; }
        public bool indicador_envia_cedula_archivo { get; set; }
        public bool indicador_nuevo_generacion_archivo { get; set; }
        public string codigo_fcm { get; set; }
        public int dia_cobro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cliente> factura_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<direccion_empresa> direccion_empresa { get; set; }
        public virtual categoria_empresa categoria_empresa { get; set; }
    }
}
