
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class factura_proveedorSRI
{

    public int id_factura_proveedorSRI { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public int ambiente { get; set; }

    public Nullable<int> anio_generacion_utilidades { get; set; }

    public string autorizacion { get; set; }

    public string autorizacion_modificado { get; set; }

    public string autorizacion_retencion { get; set; }

    public Nullable<decimal> base_imponible_diferente_cero { get; set; }

    public Nullable<decimal> base_imponible_no_objeto_iva { get; set; }

    public Nullable<decimal> base_imponible_tarifa_cero { get; set; }

    public string ciudad { get; set; }

    public string clave_acceso { get; set; }

    public string clave_acceso_liquidacion { get; set; }

    public string codigo_forma_pago_sri { get; set; }

    public string codigo_unico { get; set; }

    public string direccion_matriz { get; set; }

    public string direccion_proveedor { get; set; }

    public string direccion_sucursal { get; set; }

    public string email { get; set; }

    public string establecimiento { get; set; }

    public string establecimiento_modificado { get; set; }

    public string establecimiento_retencion { get; set; }

    public int estado { get; set; }

    public Nullable<int> estado_documento_electronico { get; set; }

    public Nullable<int> estado_documento_electronico_liquidacion { get; set; }

    public Nullable<int> estado_liquidacion { get; set; }

    public Nullable<System.DateTime> fecha_autorizacion { get; set; }

    public Nullable<System.DateTime> fecha_autorizacion_liquidacion { get; set; }

    public Nullable<System.DateTime> fecha_emision { get; set; }

    public Nullable<System.DateTime> fecha_emision_retencion { get; set; }

    public Nullable<System.DateTime> fecha_pago_dividendo { get; set; }

    public Nullable<System.DateTime> fecha_registro { get; set; }

    public int id_organizacion { get; set; }

    public int id_sucursal { get; set; }

    public string identificacion_proveedor { get; set; }

    public bool indicador_documento_electronico { get; set; }

    public bool indicador_factura_electronica { get; set; }

    public bool indicador_parte_relacionada { get; set; }

    public bool indicador_retencion_asumida { get; set; }

    public bool indicador_retencion_emitida { get; set; }

    public bool indicador_saldo_inicial { get; set; }

    public Nullable<decimal> ir_asociado_dividendo { get; set; }

    public string mensaje_sri { get; set; }

    public string mensaje_sri_liquidacion { get; set; }

    public Nullable<decimal> monto_ice { get; set; }

    public Nullable<decimal> monto_iva { get; set; }

    public string nombre_proveedor { get; set; }

    public string numero { get; set; }

    public string numero_modificado { get; set; }

    public string numero_retencion { get; set; }

    public string provincia { get; set; }

    public string punto_emision { get; set; }

    public string punto_emision_modificado { get; set; }

    public string punto_emision_retencion { get; set; }

    public string telefono_proveedor { get; set; }

    public int tipo_emision { get; set; }

    public int tipo_empresa { get; set; }

    public Nullable<decimal> total_valor_retenido { get; set; }

    public Nullable<decimal> valor_total_factura { get; set; }

    public Nullable<int> id_compra_caja_chica { get; set; }

    public Nullable<int> id_credito_tributarioSRI { get; set; }

    public Nullable<int> id_documento { get; set; }

    public Nullable<int> id_tipo_comprobante_modificado { get; set; }

    public Nullable<int> id_factura_proveedor { get; set; }

    public Nullable<int> id_pago { get; set; }

    public Nullable<int> id_tipo_comprobante { get; set; }

    public Nullable<int> id_tipo_identificacion { get; set; }

    public Nullable<int> id_autorizacion_empresa_SRI { get; set; }

    public Nullable<System.DateTime> fecha_autorizacion_proveedor_sri { get; set; }

}

}
