//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_Salida_Material
    {
        public System.DateTime FECHA_FABRICACION { get; set; }
        public string ORDEN_FABRICACION { get; set; }
        public string PLANTA { get; set; }
        public string LOTE { get; set; }
        public string CODIGO_PT { get; set; }
        public string PT { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public System.DateTime FECHA_SALIDA_MATERIAL { get; set; }
        public string PEDIDO_SALIDA { get; set; }
    }
}
