
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MateriaPrima_Lote
{

    public string codigo { get; set; }

    public string nombre { get; set; }

    public string unidad { get; set; }

    public string nombre_proveedor { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public string numero_analisis { get; set; }

    public string bodega { get; set; }

    public string bodega_liberar { get; set; }

    public Nullable<decimal> cantidad { get; set; }

    public string lote { get; set; }

    public Nullable<System.DateTime> fecha_fabricacion { get; set; }

    public System.DateTime fecha_caducidad { get; set; }

    public Nullable<System.DateTime> fecha_reanalisis { get; set; }

    public int id_producto { get; set; }

}

}
