
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MP_ME_STOCK
{

    public string COD_PRODUCTO { get; set; }

    public string NOMBRE { get; set; }

    public string CATEGORIA { get; set; }

    public string COD_CATEGORIA { get; set; }

    public string codigo { get; set; }

    public Nullable<decimal> saldo { get; set; }

    public string BODEGA { get; set; }

}

}
