
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ordenes_compra
{

    public int id_empresa { get; set; }

    public string empresa { get; set; }

    public int id_orden_compra { get; set; }

    public System.DateTime fecha { get; set; }

    public string secuencial { get; set; }

    public int id_cliente { get; set; }

    public string cliente { get; set; }

    public Nullable<decimal> valor_total { get; set; }

    public int orden_enlazada { get; set; }

}

}
