
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PickingGuias
{

    public string empresa { get; set; }

    public string secuencial { get; set; }

    public Nullable<System.DateTime> fecha_inicio_pick { get; set; }

    public string usuario_inicio_pick { get; set; }

    public Nullable<System.DateTime> fecha_fin_pick { get; set; }

    public string usuario_fin_pick { get; set; }

    public Nullable<System.DateTime> fecha_inicio_desp { get; set; }

    public string usuario_inicio_desp { get; set; }

    public Nullable<System.DateTime> fecha_fin_desp { get; set; }

    public string usuario_fin_desp { get; set; }

    public Nullable<System.DateTime> fecha_guia_troquelada { get; set; }

    public Nullable<int> diferencia { get; set; }

}

}
