//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picking_Estado
    {
        public int id_factura { get; set; }
        public Nullable<int> estado { get; set; }
        public string secuencial { get; set; }
        public string empresa { get; set; }
        public string clave_acceso { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
    }
}
