//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto_Vendedor_Detalle
    {
        public int id_presupuesto { get; set; }
        public string empresa { get; set; }
        public string sucursal { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha_desde { get; set; }
        public System.DateTime fecha_hasta { get; set; }
        public int id_vendedor { get; set; }
        public string nombre_usuario { get; set; }
        public Nullable<double> valor_cobro { get; set; }
        public Nullable<double> valor_venta { get; set; }
        public int id_presupuesto_detalle { get; set; }
    }
}
