
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class presupuesto_detalle
{

    public int id_presupuesto_cabecera { get; set; }

    public int id_vendedor { get; set; }

    public Nullable<double> valor_venta { get; set; }

    public Nullable<double> valor_cobro { get; set; }

    public int id_presupuesto_detalle { get; set; }



    public virtual presupuesto_cabecera presupuesto_cabecera { get; set; }

}

}
