
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class producto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public producto()
    {

        this.producto1 = new HashSet<producto>();

    }


    public int id_producto { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public bool activo { get; set; }

    public decimal cantidad_maxima { get; set; }

    public decimal cantidad_minima { get; set; }

    public int cantidad_minima_venta { get; set; }

    public int cantidad_minimo_kit { get; set; }

    public decimal cantidad_perdida { get; set; }

    public decimal cantidad_produccion { get; set; }

    public string codigo { get; set; }

    public string codigo_alterno { get; set; }

    public string codigo_barras { get; set; }

    public string codigo_categoria_producto { get; set; }

    public string codigo_comercial { get; set; }

    public string codigo_fiscal { get; set; }

    public string codigo_ice { get; set; }

    public string codigo_subcategoria_producto { get; set; }

    public decimal coeficiente_produccion { get; set; }

    public Nullable<decimal> costo_estandar { get; set; }

    public decimal costo_indirecto_presupuestado { get; set; }

    public Nullable<int> criterio_actualizacion_lista_precio { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> dias_caducidad { get; set; }

    public decimal factor_perdida { get; set; }

    public Nullable<System.DateTime> fecha_ultima_compra { get; set; }

    public Nullable<System.DateTime> fecha_ultima_venta { get; set; }

    public string ibp_codigo_impuesto { get; set; }

    public string ibp_grado_alcohol { get; set; }

    public string ibp_presentacion { get; set; }

    public decimal ice { get; set; }

    public string ice_clasificacion { get; set; }

    public decimal ice_gramos_azucar { get; set; }

    public string ice_marca { get; set; }

    public string ice_presentacion { get; set; }

    public int id_categoria_producto { get; set; }

    public int id_organizacion { get; set; }

    public int id_subcategoria_producto_field { get; set; }

    public int id_sucursal { get; set; }

    public string imagen { get; set; }

    public string imagen_calidad { get; set; }

    public Nullable<bool> impuesto_aviacion { get; set; }

    public bool indicador_agregar_con_saldo_cero { get; set; }

    public bool indicador_califica_proveedor { get; set; }

    public bool indicador_compra { get; set; }

    public bool indicador_consumo { get; set; }

    public bool indicador_consumo_directo { get; set; }

    public bool indicador_control_calidad { get; set; }

    public bool indicador_es_cotizable { get; set; }

    public Nullable<bool> indicador_explota_devolucion { get; set; }

    public bool indicador_horas_post_consumo { get; set; }

    public bool indicador_impuestos { get; set; }

    public bool indicador_incluir_pedido_sugerido { get; set; }

    public bool indicador_lista_material { get; set; }

    public bool indicador_lote { get; set; }

    public bool indicador_maneja_impuesto { get; set; }

    public bool indicador_maneja_unidad_informativa { get; set; }

    public Nullable<bool> indicador_manejo_peso { get; set; }

    public bool indicador_mantenimiento { get; set; }

    public Nullable<bool> indicador_nacional { get; set; }

    public bool indicador_despacho_gaveta { get; set; }

    public bool indicador_planificar_produccion { get; set; }

    public bool indicador_porcentaje_ice { get; set; }

    public bool indicador_post_consumo { get; set; }

    public bool indicador_produccion { get; set; }

    public bool indicador_produccion_kit { get; set; }

    public bool indicador_produccion_rapida { get; set; }

    public bool indicador_seleccion_unica { get; set; }

    public Nullable<bool> indicador_serie { get; set; }

    public bool indicador_sujeto_seleccion { get; set; }

    public bool indicador_tiene_movimientos { get; set; }

    public bool indicador_valida_produccion_osm { get; set; }

    public bool indicador_venta { get; set; }

    public string informacion_adicional { get; set; }

    public decimal maximo_desvio { get; set; }

    public int meses_planificacion_compra { get; set; }

    public Nullable<int> multiplo_pedido { get; set; }

    public decimal multiplo_ventas { get; set; }

    public string nombre { get; set; }

    public string nombre_categoria_producto { get; set; }

    public string nombre_comercial { get; set; }

    public string nombre_subcategoria_producto { get; set; }

    public Nullable<int> orden_costeo { get; set; }

    public string pdf { get; set; }

    public Nullable<decimal> peso { get; set; }

    public Nullable<decimal> peso_destare_unidad { get; set; }

    public Nullable<decimal> peso_maximo { get; set; }

    public Nullable<decimal> peso_minimo { get; set; }

    public Nullable<int> porciento_despacho_supera_pedido { get; set; }

    public decimal porcentaje_criterio { get; set; }

    public decimal porcentaje_devolucion { get; set; }

    public int porciento_tolerancia_transferencia { get; set; }

    public decimal precio_referencial_compra { get; set; }

    public decimal precio_referencial_venta { get; set; }

    public decimal precio_ultima_compra { get; set; }

    public decimal precio_ultima_venta { get; set; }

    public bool predeterminado { get; set; }

    public string prefijo_lote { get; set; }

    public string prefijos_lote { get; set; }

    public Nullable<decimal> saldo_acumulado { get; set; }

    public Nullable<decimal> saldo_disponible { get; set; }

    public Nullable<decimal> saldo_por_despachar { get; set; }

    public decimal subsidio { get; set; }

    public string sufijo_lote { get; set; }

    public int tiempo_reposicion { get; set; }

    public int tipo_costo { get; set; }

    public Nullable<int> tipo_producto_formulacion { get; set; }

    public int tipo_producto { get; set; }

    public Nullable<int> tipo_valor_criterio_actualizacion_lista_precio { get; set; }

    public decimal tolerancia_solicitud_transferencia { get; set; }

    public decimal valor_ibp { get; set; }

    public int version_costeo { get; set; }

    public decimal volumen { get; set; }

    public Nullable<int> id_atributo_produccion_1 { get; set; }

    public Nullable<int> id_atributo_produccion_10 { get; set; }

    public Nullable<int> id_atributo_produccion_2 { get; set; }

    public Nullable<int> id_atributo_produccion_3 { get; set; }

    public Nullable<int> id_atributo_produccion_4 { get; set; }

    public Nullable<int> id_atributo_produccion_5 { get; set; }

    public Nullable<int> id_atributo_produccion_6 { get; set; }

    public Nullable<int> id_atributo_produccion_7 { get; set; }

    public Nullable<int> id_atributo_produccion_8 { get; set; }

    public Nullable<int> id_atributo_produccion_9 { get; set; }

    public Nullable<int> id_bodega_compra { get; set; }

    public Nullable<int> id_bodega_venta { get; set; }

    public Nullable<int> id_casa_comercial { get; set; }

    public Nullable<int> id_categoria_impuesto { get; set; }

    public Nullable<int> id_conjunto_atributo { get; set; }

    public Nullable<int> id_credito_tributarioSRI { get; set; }

    public Nullable<int> id_empresa { get; set; }

    public Nullable<int> id_ibp_capacidad { get; set; }

    public Nullable<int> id_ibp_marca { get; set; }

    public Nullable<int> id_ibp_unidad { get; set; }

    public Nullable<int> id_marca_producto { get; set; }

    public Nullable<int> id_partida_arancelaria { get; set; }

    public Nullable<int> id_presentacion_producto { get; set; }

    public Nullable<int> id_producto_transformacion_automatica { get; set; }

    public Nullable<int> id_ruta_fabricacion { get; set; }

    public int id_subcategoria_producto { get; set; }

    public int id_unidad { get; set; }

    public Nullable<int> id_unidad_almacenamiento { get; set; }

    public Nullable<int> id_unidad_compra { get; set; }

    public Nullable<int> id_unidad_informativa { get; set; }

    public Nullable<int> id_unidad_presupuesto { get; set; }

    public Nullable<int> id_unidad_venta { get; set; }

    public bool indicador_lista_accesorio { get; set; }

    public int numero_accesorios { get; set; }

    public Nullable<int> id_color_producto { get; set; }

    public Nullable<int> id_tipo_accesorio { get; set; }

    public bool indicador_tipo_unidad_manejo { get; set; }

    public Nullable<int> porcentaje_recepcion_supera_pedido { get; set; }

    public decimal coeficiente_utilizacion_maquina { get; set; }

    public decimal multiplo_ventas_ecommerce { get; set; }

    public Nullable<decimal> porcentaje_iva_presuntivo { get; set; }

    public Nullable<bool> indicador_reposicion_bajo_consumo { get; set; }



    public virtual empresa empresa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<producto> producto1 { get; set; }

    public virtual producto producto2 { get; set; }

}

}
