
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Proveedores
{

    public string empresa { get; set; }

    public string codigo { get; set; }

    public string nombre_fiscal { get; set; }

    public string nombre_comercial { get; set; }

    public string provincia { get; set; }

    public string ciudad { get; set; }

    public string parroquia { get; set; }

    public string codigo_postal { get; set; }

    public string telefono { get; set; }

    public string telefono2 { get; set; }

    public string direccion { get; set; }

    public string correo { get; set; }

    public string categoria_empresa { get; set; }

}

}
