
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class prov_oc_principal
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public prov_oc_principal()
    {

        this.prov_oc_detalle = new HashSet<prov_oc_detalle>();

    }


    public int id_oc_principal { get; set; }

    public int id_proveedor { get; set; }

    public System.DateTime fecha_documento { get; set; }

    public decimal valor_total { get; set; }

    public bool anulada { get; set; }

    public int id_organizacion { get; set; }

    public int id_departamento { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<prov_oc_detalle> prov_oc_detalle { get; set; }

}

}
