
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Reporte_Consolidado_Cierre
{

    public string empresa { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public string numero_consolidado { get; set; }

    public string numero_cobro { get; set; }

    public string recaudador { get; set; }

    public decimal valor_cobro { get; set; }

    public decimal valor_total { get; set; }

    public int id_consolidado_cierre { get; set; }

}

}
