//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte_GuiasRemision
    {
        public string empresa { get; set; }
        public string nombre_comercial { get; set; }
        public string secuencial_factura { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public string secuencial_guia { get; set; }
        public Nullable<System.DateTime> fecha_guia { get; set; }
        public string ciudad { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<int> bultos { get; set; }
        public string serial_urbano { get; set; }
        public string nota_guia { get; set; }
    }
}
