
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class secuencia
{

    public int id_secuencia { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public int desde { get; set; }

    public System.DateTime fecha_desde { get; set; }

    public System.DateTime fecha_hasta { get; set; }

    public int hasta { get; set; }

    public int id_organizacion { get; set; }

    public Nullable<int> id_sucursal { get; set; }

    public Nullable<bool> indicador_bloqueada { get; set; }

    public int longitud { get; set; }

    public string nombre { get; set; }

    public int numero { get; set; }

    public string prefijo { get; set; }

    public string sufijo { get; set; }

}

}
