//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id_producto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string codigo_categoria { get; set; }
        public string categoria { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public string bodega { get; set; }
        public Nullable<int> id_lote { get; set; }
        public string lote { get; set; }
    }
}
