//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transito_MP_ME_pedido
    {
        public int id_material { get; set; }
        public string nombre_material { get; set; }
        public string um { get; set; }
        public Nullable<decimal> cantidad { get; set; }
    }
}
