//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oasis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transito_PT_Total
    {
        public string Código_producto { get; set; }
        public string nombre { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public Nullable<decimal> Cantidad_transito_total { get; set; }
    }
}
