
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class usuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public usuario()
    {

        this.factura_cliente = new HashSet<factura_cliente>();

    }


    public int id_usuario { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<System.DateTime> fecha_modificacion { get; set; }

    public Nullable<int> id_entidad_origen { get; set; }

    public string usuario_creacion { get; set; }

    public string usuario_modificacion { get; set; }

    public string IP { get; set; }

    public bool activo { get; set; }

    public string clave { get; set; }

    public string codigo { get; set; }

    public string descripcion { get; set; }

    public string direccion { get; set; }

    public string email { get; set; }

    public bool en_linea { get; set; }

    public int genero { get; set; }

    public string identificacion { get; set; }

    public bool indicador_administrador { get; set; }

    public bool indicador_agente_comercial { get; set; }

    public Nullable<bool> indicador_aprobador { get; set; }

    public bool indicador_autoriza_despacho { get; set; }

    public bool indicador_autoriza_ventas { get; set; }

    public bool indicador_cierre_caja_masivo { get; set; }

    public bool indicador_maneja_cuentas_contables { get; set; }

    public bool indicador_nuevo { get; set; }

    public bool indicador_recibe_notificaciones { get; set; }

    public Nullable<bool> solo_lectura { get; set; }

    public bool indicador_usuario_pos { get; set; }

    public bool indicador_ver_costo { get; set; }

    public string nombre1 { get; set; }

    public string nombre2 { get; set; }

    public string nombre_usuario { get; set; }

    public bool obligatorio_logeo_biometrico_huella { get; set; }

    public bool permitir_sesion_desde_otra_IP { get; set; }

    public bool predeterminado { get; set; }

    public string telefono { get; set; }

    public string tema { get; set; }

    public int tipo_usuario_revisor { get; set; }

    public int tipo_visualizacion { get; set; }

    public Nullable<int> id_dispositivo { get; set; }

    public Nullable<int> id_empleado { get; set; }

    public Nullable<int> id_plan_comision { get; set; }

    public Nullable<int> id_recaudador { get; set; }

    public Nullable<int> id_tipo_vendedor { get; set; }

    public string roles { get; set; }

    public bool indicador_ingreso_ldap { get; set; }

    public bool indicador_modifica_valor_promocion { get; set; }

    public string consultas_entidad { get; set; }

    public string IP_auditoria { get; set; }

    public string codigo_fcm { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<factura_cliente> factura_cliente { get; set; }

}

}
