
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class V_cobros_tmp
{

    public int id_cobro { get; set; }

    public string empresa { get; set; }

    public string sucursal { get; set; }

    public Nullable<System.DateTime> fecha_inicio { get; set; }

    public Nullable<System.DateTime> fecha_fin { get; set; }

    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public Nullable<int> estado { get; set; }

    public string usuario_creacion { get; set; }

}

}
