
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class V_cobros_empresa
{

    public string empresa { get; set; }

    public int id_cobro { get; set; }

    public string descripcion { get; set; }

    public string numero { get; set; }

    public string descripcion2 { get; set; }

    public int estado { get; set; }

    public string codigo_movil { get; set; }

    public System.DateTime fecha { get; set; }

    public int id_empresa { get; set; }

}

}
