
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oasis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ventas_Producto_Precio
{

    public int id_organizacion { get; set; }

    public string Empresa { get; set; }

    public Nullable<int> id_sucursal { get; set; }

    public string localidad { get; set; }

    public string identificacion { get; set; }

    public string Cliente { get; set; }

    public string factura { get; set; }

    public string codigo_producto { get; set; }

    public string producto { get; set; }

    public decimal cantidad { get; set; }

    public decimal bonificacion { get; set; }

    public Nullable<decimal> porc_bonifica { get; set; }

    public decimal valores { get; set; }

    public Nullable<decimal> precio { get; set; }

    public decimal precio_especial { get; set; }

    public Nullable<System.DateTime> fecha_factura { get; set; }

    public string tipo_documento { get; set; }

}

}
